### ISSUE TITLE
Ошибка в порядке элементов урл

### ISSUE THREAD

**Issue by workism** [AutoDealerRu/catalog-api-documentation#2]
https://github.com/AutoDealerRu/catalog-api-documentation/blob/master/a2d/1_models.md
Написано в мануале 
> GET /:mark/:category

А по факту наоборот  /:category/:mark

> curl -H 'Authorization: <token>'  -X GET https://acat.online/api/catalogs/CARS_NATIVE/VAZ

**Comment by launcelot66** [comment]
Спасибо, поправлю завтра
26.03.2017 2:49 пользователь "Стас Иванов" <notifications@github.com>
написал:
>
>
https://github.com/AutoDealerRu/catalog-api-documentation/blob/master/a2d/1_models.md
> Написано в мануале
>>
>> GET /:mark/:category
>
> А по факту наоборот /:category/:mark
> curl -H 'Authorization: ' -X GET
https://acat.online/api/catalogs/CARS_NATIVE/VAZ

**Comment by workism** [comment]
В остальных тоже так же https://github.com/AutoDealerRu/catalog-api-documentation/blob/master/a2d/2_groups.md
