### ISSUE TITLE
Проблема валидации частей урл

### ISSUE THREAD

**Issue by workism** [AutoDealerRu/catalog-api-documentation#3]
Это не совсем баг, но создает проблемы при работе с урлами

Дело в том, что в фреймворках для задания урлов нужно указывать regex какие символы там могут быть

Например
```python
url(r'^models/(?P<category>[a-zA-Z_]+)/(?P<mark>[0-9a-zA-Z_-]+)/$', views.models, name='autocatalog_models'),

```

А у вас встречаются значения для урлов непредсказуемые
> KOMAT'SU_ENGINE

На данный момент regexp для марки является
> (?P<mark>[0-9a-zA-Z_\'-]+)

Можно ли считать его верным ? Можно ли указать подобные правила для остальных компонентов урла ?

**Comment by Nazgard** [comment]
В имени марки, модели, модификации, группы и т.д. могут использоваться все печатаемые символы (с 33го по 126ой символы таблицы ASCII).

Тогда regexp получается такой:
```
(\S+)
```

**Comment by workism** [comment]
Тогда как быть с символами / & ? , они же воспринимаются как системные части урла ? В случае построения красивых урлов они могут срабатывать ошибочно, например
`https://acat.online/api/catalogs/CARS_NATIVE/VA/Z` не будет работать

**Comment by Nazgard** [comment]
Символы / & ? кодируются по стандарту RFC 3986. Т.е. символ / должен быть закодирован в %2F.

https://ru.wikipedia.org/wiki/URL#.D0.9A.D0.BE.D0.B4.D0.B8.D1.80.D0.BE.D0.B2.D0.B0.D0.BD.D0.B8.D0.B5_URL

**Comment by workism** [comment]
В случае с apache будет ошибка даже с %2F. Гдето у меня была ссылка на проблему

**Comment by workism** [comment]
Кажется нашел по %2F, похоже что урл не должен содержать некоторых символов даже в закодированном виде

http://stackoverflow.com/questions/9206835/2f-in-url-breaks-and-does-not-reference-to-the-php-file-required
http://stackoverflow.com/questions/28548450/2f-not-accepted-in-url-by-apache

Но это не касается GET параметров, там может быть любой символ

**Comment by launcelot66** [comment]
@workism Сюдя по тому, что пишут на стаке - это лечится через httpd.cond + перезагрузкой сервера, поэтому урл может содержать %2F
