### ISSUE TITLE
На запрос изображения сервер отвечает ошибкой 404

### ISSUE THREAD

**Issue by Morjodrom** [AutoDealerRu/catalog-api-documentation#4]
Пытаюсь получить изображение по ссылке 
https://acat.online/api/catalogs/CARS_NATIVE/VAZ/58961/3373769/image
Nginx отвечает 404 кодом, тело ответа пустое.

Ссылку получил из JSON после запроса к https://acat.online/api/catalogs/CARS_NATIVE/VAZ/58961/3373769 (используюется в документации в [примере](https://github.com/AutoDealerRu/catalog-api-documentation/blob/master/a2d/3_numbers.md))

Токен авторизации верный.

**Update:**
В принципе, запрос изображений узлов не работает: та же ситуация с ссылкой на api/catalogs/CARS_FOREIGN/FORD_SKD/39826/2236377/image

**Comment by launcelot66** [comment]
@Morjodrom изображение можно получить только отправив в в заголовке запроса Authorization: your_token
Т.е. для загрузки изображений конечных Вам нужно создать где-то файл, например в корне getimg.php
он будет принимать $_GET параметр path (путь до картинки), получится например так:
`<img src="getimg.php?path=https%3A%2F%2Facat.online%2Fapi%2Fcatalogs%2FCARS_NATIVE%2FVAZ%2F58961%2F3373769%2Fimage">
`
внутри делаете отправку запроса с токеном в заголовке и тогда в ответ придет изображение

**Comment by Morjodrom** [comment]
Запрос осуществлял через REST client IDE, токен авторизации в заголовках, все, кроме запросов к изображениям, работает. Эмуляция запроса через браузер, с подстановкой authorization token также не приводила к результату. Запрос к изображению без authorization token в принципе был невозможен, т.к. возвращает ответ об отсутствии авторизации ({"code":404,"message":"Не найден пользователь"}).

**Запрос** к api/catalogs/CARS_FOREIGN/KIA/EUR/CARENS/EURK1D006A/BKWDS65/AC/AC004457EU/image 

**Authorization token** проставлен.

**Заголовки ответа сервера:**
HTTP/1.1 404 Image not found
Server: nginx/1.10.2
Date: Thu, 06 Apr 2017 09:36:06 GMT
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: Express
Strict-Transport-Security: max-age=31536000; includeSubDomains

**Comment by launcelot66** [comment]
@Morjodrom в данном случае картинки нет, поэтому отдается статус 404, но в теле присутствует изображение-заглушка, можете посмотреть перейдя по ссылке
https://acat.online/catalogs/CARS_FOREIGN/KIA/EUR/CARENS/EURK1D006A/BKWDS65/AC/AC004457EU/image

**Comment by Morjodrom** [comment]
@launcelot66 именно в этом и состоит вопрос: почему по запросу нет картинки - это штатная ситуация или ошибка? И где посмотреть пример, чтоб картинка была?

**Comment by launcelot66** [comment]
@Morjodrom https://acat.online/catalogs/CARS_NATIVE/VAZ/58961/3373769 - тут ссылка на картинку https://acat.online/catalogs/CARS_NATIVE/VAZ/58961/3373769/image - изображение присутствует, статус 200 отдается, на 404 статусе заглушка стоит "не найдено" - это на тот случай, если есть своя заглушка, чтобы не ждать загрузки, а сразу проверив статус отдать свое изображние "изображение отсутствует"

**Comment by Morjodrom** [comment]
> https://acat.online/catalogs/CARS_NATIVE/VAZ/58961/3373769 - тут ссылка на картинку 
https://acat.online/catalogs/CARS_NATIVE/VAZ/58961/3373769/image - изображение присутствует.

Все верно. Вопрос о заглушках нас не интересует - тут все понятно.

Как эту картинку получить по **api**? 

В параметре "image" объекта group в ответе на запрос к REST API  https://acat.online/api/catalogs/CARS_NATIVE/VAZ/58914/3369656 приходит ссылка https://acat.online/api/catalogs/CARS_NATIVE/VAZ/58961/3373769/image - делаем на неё запрос и получаем ответ с кодом 404 и пустым телом.  При этом для того же самого объекта ссылка, которая не относится к API - https://acat.online/catalogs/CARS_NATIVE/VAZ/58914/3369656/image , нормально отдает изображение. 

Интересует вопрос, как получить картинку по REST API? Либо не работающую ссылку, полученную по REST API необходимо самостоятельно изменять так, чтобы получилась работающая ссылка не REST API?

**Comment by launcelot66** [comment]
@Morjodrom Ошибка исправлена, можете проверить, изображение теперь отдается через api
